### ISSUE TITLE
Error when silverstripe-elemental-virtual not present

### ISSUE THREAD

**Issue by tardinha** [nswdpc/silverstripe-elemental-modeladmin#4]
[Error here](https://github.com/nswdpc/silverstripe-elemental-modeladmin/blob/master/src/Controllers/ElementModelAdmin.php#L92) when [silverstripe-elemental-virtual extension](https://github.com/dnadesign/silverstripe-elemental-virtual/blob/master/src/Extension/BaseElementExtension.php#L39) is not installed.

**Comment by JamesDPC** [comment]
Fixed in v0.1.3
